### ISSUE TITLE
Unit property annotation

### ISSUE THREAD

**Issue by alumni** [oasis-tcs/odata-vocabularies#179]
Currently it is possible to define the currency/unit of a measure only by using a constant, e.g. by setting `@Measures.ISOCurrency` of a property called `Amount` to `"EUR"` - this would mean that the amount is always expressed in euros. However, there are cases when the amount is expressed in various currencies and the currency for each entry is set in another property. Currently it is not possible to set a property as the unit of another property (e.g. I have two properties, `Amount` and `Currency` and I'd like to annotate somehow that the currency for `Amount` can be found in the `Currency` property). Are there any plans to allow this?

**Comment by HeikoTheissen** [comment]
According to the OData specification, it is always possible to express the value of an annotation dynamically, through a [path expression](https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_PathExpressions). In your example, the annotation would be (in CSDL JSON notation):
```json
"Amount@Measures.ISOCurrency": {"$Path": "Currency"}
```
assuming that both properties belong to the same entity type.

I hope this answers your question.
