### ISSUE TITLE
How to annotate NonInsertableProperties and NonUpdatableProperties for contained entities

### ISSUE THREAD

**Issue by ralfhandl** [oasis-tcs/odata-vocabularies#247]
I'm trying to implement `InsertRestrictions/NonInsertableProperties` in the [OpenAPI Generator](https://github.com/oasis-tcs/odata-openapi) and wonder which of three annotation flavors to support for models with containment navigation.

Assume a model
~~~mermaid
classDiagram
  defcon *-- Header
  Header *-- Item
  class defcon {
    <<EntityContainer>>
    Headers: [this.Header]
  }
  class Header {
    ...
    NotAlwaysInsertableH: String
    _items: [this.Item]
  }
  class Item {
    ...
    NotAlwaysInsertableI: String
  }
  
~~~

Would I annotate this as
1. on the root entity set for both direct properties and properties of contained entities: 
~~~xml
<Annotations Target="this.defcon/Headers">
  <Annotation Term="Capabilities.InsertRestrictions">
    <Record>
      <PropertyValue Property="NonInsertableProperties">
        <Collection>
          <PropertyPath>NotAlwaysInsertableH</PropertyPath>
          <PropertyPath>_items/NotAlwaysInsertableI</PropertyPath>
        </Collection>
      </PropertyValue>
    </Record>
  </Annotation>
</Annotations>
~~~
2. use `InsertRestrictions/NonInsertableProperties` only for properties of `Header` and 
   1. add `NavigationRestrictions` for `_items` with `InsertRestrictions/NonInsertableProperties` for properties of `_items`, or 
   2. use `InsertRestrictions` with `Target="this.defcon/Headers/_items"` for properties of `_items`?

**Comment by HeikoTheissen** [comment]
In https://github.com/oasis-tcs/odata-vocabularies/blob/main/examples/Org.OData.Capabilities.V1.capabilities.md we have favored option 2.ii over option 2.i. We have not mentioned option 1 at all there.

**Comment by ralfhandl** [comment]
For `CountRestrictions` and `ExpandRestrictions` option 1 is the only available option, so I tend to allow and explicitly mention it.

**Comment by ralfhandl** [comment]
Resolution: 
- Option 1 is valid, add it to https://github.com/oasis-tcs/odata-vocabularies/blob/main/examples/Org.OData.Capabilities.V1.capabilities.md
- Option 2.ii is preferred, but SAP can use the "second best" option 1
