### ISSUE TITLE
Non-uniform wording for `Validation.ApplicableTerms`

### ISSUE THREAD

**Issue by HeikoTheissen** [oasis-tcs/odata-vocabularies#275]
https://github.com/oasis-tcs/odata-vocabularies/blob/0867919485149d8636d0b04b06c4ab0860fbd67d/lib/csdl2markdown.js#L614

vs.

https://github.com/oasis-tcs/odata-vocabularies/blob/0867919485149d8636d0b04b06c4ab0860fbd67d/lib/csdl2markdown.js#L481

Is this intended?

**Comment by ralfhandl** [comment]
The first is within a table cell, the second in normal text.

Maybe this difference is no longer needed with your updated build process.

**Comment by HeikoTheissen** [comment]
> Maybe this difference is no longer needed with your updated build process

The wording could be uniform even with the old build process.

**Comment by ralfhandl** [comment]
It definitely broke the "very old" build process 😎

**Comment by ralfhandl** [comment]
We can definitely use the same wording in both places. Which of the variants do you prefer?

**Comment by ralfhandl** [comment]
And we could switch from Markdown tables to HTML tables and use the same formatting in both cases.

**Comment by HeikoTheissen** [comment]
> And we could switch from Markdown tables to HTML tables and use the same formatting in both cases.

I'd prefer to use Markdown where it is possible.
