### ISSUE TITLE
Boolean Casing Issue in Org.OData.Capabilities.V1.xml

### ISSUE THREAD

**Issue by mraineri** [oasis-tcs/odata-vocabularies#31]
The Term `AnnotationValuesInQuerySupported` contains `DefaultValue="True"` as an attribute. However, the Entity Data Model definition defines a boolean as either `true` or `false` (lower case t), so `DefaultValue` should be changed to `"true"`.

**Comment by ralfhandl** [comment]
@mraineri thanks for pointing this out!
