### ISSUE TITLE
Possible Usage Problem of Edm.EntityType in Org.OData.Core.V1.xml

### ISSUE THREAD

**Issue by mraineri** [oasis-tcs/odata-vocabularies#32]
The ComplexType `EntityExampleValue` contains a single Property element, and its Type attribute is set to `Edm.EntityType`. However, the CSDL specification states that for Property elements, the Type attribute must either be a Primitive Type, Complex Type, Enumeration Type, or a Collection of the above. As far as I can tell, `Edm.EntityType` does not qualify as any of those. Is my understanding of the restriction in the specification correct?

**Comment by ralfhandl** [comment]
@mraineri Thanks for pointing this out. Your interpretation of the specification is correct, and this use of Edm.EntityType is invalid.

The OData TC will discuss how to fix this.
