### ISSUE TITLE
the Type of the Edm Term for LabeledElement, IsOf....

### ISSUE THREAD

**Issue by xuzhg** [oasis-tcs/odata-vocabularies#47]
HI, TC

From OData XML CSDL spec, it says:

### Element edm:Term

The edm:Term element MUST contain the attributes Name and Type.

so, What's the **Type** of the term which is used with "Is-Of", "Cast", "Labeled Element", ... etc.

for example:
```xml
<Annotation Term="self.IsPreferredCustomer">
  <IsOf Type="self.PreferredCustomer">
    <Path>Customer</Path>
  </IsOf>
</Annotation>
```

What's the Type for the Term (self.IsPreferrredCustomer)?

**Comment by ralfhandl** [comment]
The IsOf expression returns a Boolean, so term IsPreferredCustomer must also be of type Boolean.

**Comment by xuzhg** [comment]
@ralfhandl How about "LabeledElement"?

**Comment by ralfhandl** [comment]
[14.4.9 Labeled Element](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/cs01/odata-csdl-xml-v4.01-cs01.html#sec_LabeledElement) says

> The value of the child expression is also the value of the labeled element expression.

**Comment by xuzhg** [comment]
@ralfhandl Thanks. 

I mean what's the **Type** of term **org.example.display.DisplayName** in the following examples:

```json
<Annotation Term="org.example.display.DisplayName">
  <LabeledElementReference>Model.CustomerFirstName</LabeledElementReference>
</Annotation>
```

and

```json
<Annotation Term="org.example.display.DisplayName">
  <LabeledElement Name="CustomerFirstName" Path="FirstName" />
</Annotation>
```

**Comment by ralfhandl** [comment]
That's a made-up term. As the labeled element is defined within an annotation with the same term as the one within which it is referenced, the type is naturally the same, no matter what type the hypothetical DisplayName has.
