### ISSUE TITLE
Does the ReadRestrictions term type should be "ReadRestrictionsBase"

### ISSUE THREAD

**Issue by xuzhg** [oasis-tcs/odata-vocabularies#49]
Hi

The term definition in 
https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml#L795

```xml
<Term Name="ReadRestrictions" Type="Capabilities.ReadRestrictionsType" AppliesTo="EntitySet Singleton FunctionImport">
  <Annotation Term="Core.Description"
          String="Restrictions for retrieving a collection of entities, retrieving a singleton instance, invoking a function" />
</Term>
```

The type should be "ReadRestrictionsBase" ?

And 

https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml#L904

```xml
<Property Name="ExampleValues" Type="Collection(Core.PrimitiveExampleValue)" Nullable="false">
       <Annotation Term="Core.Description" String="Example values for the custom parameter" />
</Property>
```

the type should be "Collection(Core.ExampleValue)" ?

**Comment by ralfhandl** [comment]
ReadRestrictions: no, this is intended. ReadRestrictions has a property ReadByKeyRestrictions, which has a similar structure as ReadRestrictions, just without the ReadByKeyRestrictions.

CustomParameter: a custom parameter is a header or a query option and thus always has a primitive value.
