### ISSUE TITLE
Type of AcceptableMediaTypes  is not same with MD and xml & json

### ISSUE THREAD

**Issue by xuzhg** [oasis-tcs/odata-vocabularies#99]
https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.md 

says AcceptableMediaTypes  is a collection of [MediaType],

AcceptableMediaTypes | [MediaType] | Lists the MIME types acceptable for the annotated entity type marked with HasStream="true" or the annotated binary, stream, or string property or term
-- | -- | --

https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.xml#L389
says: 

AcceptableMediaTypes  is a collection of [String],

`<Term Name="AcceptableMediaTypes" Type="Collection(Edm.String)"`

I know "MediaType" is a type definition, its underline type is "Edm.String".

However, the "MD" file content should be consistent with "xml" and "json" file.

**Comment by ralfhandl** [comment]
Hi @xuzhg, URLs and media types have a special role in REST, so they are "highlighted" in the generated markdown.

This is based on annotations with terms Core.IsURL or Core.IsMediaType. 

The markdown is tailored for human readers: some things are intentionally left out, and some things appear more prominently.
